using Test1.Contracts;
using Test1.Models;
using Dapper;
using System.Transactions;

namespace Test1.Repository
{
    public class MemberRepository : IMemberRepository
    {
        private readonly ISessionFactory _sessionFactory;

        public MemberRepository(ISessionFactory sessionFactory)
        {
            _sessionFactory = sessionFactory;
        }

        // List all members or optionally by AccountUid
        public async Task<IEnumerable<Member>> ListMembers(CancellationToken cancellationToken)
        {
            await using var dbContext = await _sessionFactory.CreateContextAsync(cancellationToken)
                .ConfigureAwait(false);

            string sql = @"
SELECT
    UID,
    Guid,
    AccountUid,
    LocationUid,
    CreatedUtc,
    UpdatedUtc,
    ""Primary"",
    JoinedDateUtc,
    CancelDateUtc,
    FirstName,
    LastName,
    Address,
    City,
    Locale,
    PostalCode,
    Cancelled
FROM member";

            

            var result = await dbContext.Session.QueryAsync<Member>(
                sql,
                transaction:
                dbContext.Transaction
            );

            dbContext.Commit();
            return result;
        }


         // Create member, ensuring only one primary per account
        public async Task<Member> CreateMember(Member newMember, CancellationToken cancellationToken)
        {
            await using var db = await _sessionFactory.CreateContextAsync(cancellationToken)
                .ConfigureAwait(false);

            // If new member is primary, set all other members of the account to non-primary
            if (newMember.Primary)
            {
                // 0 = false, 1 = true
                const string resetPrimarySql = @"
UPDATE member
SET ""Primary"" = 0
WHERE AccountUid = @AccountUid;";

                await db.Session.ExecuteAsync(resetPrimarySql, new { newMember.AccountUid }, db.Transaction)
                    .ConfigureAwait(false);
            }

            // Insert new member
            const string insertSql = @"
INSERT INTO member (
    Guid,
    AccountUid,
    LocationUid,
    CreatedUtc,
    UpdatedUtc,
    ""Primary"",
    JoinedDateUtc,
    CancelDateUtc,
    FirstName,
    LastName,
    Address,
    City,
    Locale,
    PostalCode,
    Cancelled
) VALUES (
    @Guid,
    @AccountUid,
    @LocationUid,
    @CreatedUtc,
    @UpdatedUtc,
    @Primary,
    @JoinedDateUtc,
    @CancelDateUtc,
    @FirstName,
    @LastName,
    @Address,
    @City,
    @Locale,
    @PostalCode,
    @Cancelled
);";

            newMember.Guid = Guid.NewGuid();
            newMember.CreatedUtc = DateTime.UtcNow;
            newMember.UpdatedUtc = DateTime.UtcNow;

            await db.Session.ExecuteAsync(insertSql, newMember, db.Transaction)
                .ConfigureAwait(false);

            // Retrieve UID generated by SQLite
            newMember.Uid = await db.Session.ExecuteScalarAsync<int>(
                "SELECT last_insert_rowid();", transaction: db.Transaction);

            db.Commit();
            return newMember;
        }

        // Delete a member by UID
    public async Task<int> DeleteMember(int uid, CancellationToken cancellationToken)
{
    await using var db = await _sessionFactory.CreateContextAsync(cancellationToken)
        .ConfigureAwait(false);

    // 1. Get the member to delete
    var memberToDelete = await db.Session.QueryFirstOrDefaultAsync<Member>(
        "SELECT * FROM member WHERE UID = @UID;", new { UID = uid }, db.Transaction);

    if (memberToDelete == null)
        return 0; // Member not found

    // 2. Count how many members exist for this account
    var membersCount = await db.Session.ExecuteScalarAsync<int>(
        "SELECT COUNT(*) FROM member WHERE AccountUid = @AccountUid;",
        new { memberToDelete.AccountUid }, db.Transaction);

    if (membersCount <= 1)
        throw new InvalidOperationException("Cannot delete the last member of an account.");

    // 3. Delete the member
    const string deleteSql = "DELETE FROM member WHERE UID = @UID;";
    var deleted = await db.Session.ExecuteAsync(deleteSql, new { UID = uid }, db.Transaction);

    // 4. Promote next member if deleted member was primary
    if (memberToDelete.Primary)
    {
        const string promoteSql = @"
UPDATE member
SET ""Primary"" = 1
WHERE UID = (
    SELECT UID FROM member
    WHERE AccountUid = @AccountUid
    ORDER BY JoinedDateUtc ASC
    LIMIT 1
);";

        await db.Session.ExecuteAsync(promoteSql, new { memberToDelete.AccountUid }, db.Transaction);
    }

    db.Commit();
    return deleted;
}


      
    }
}
